### ISSUE TITLE
Wait for reboot doesn't always wort

### ISSUE THREAD

**Issue by badnetmask** [RedHatOfficial/ansible-redhat_cloudforms#25]
https://github.com/RedHatOfficial/ansible-redhat_cloudforms/blob/50b952a582871965c9c8a39d9345df4ce249f79d/tasks/host-reboot.yml#L27

The above variable translates to the host name without a domain, which may cause the wait for reboot operation to fail, if the host where you're running the playbook from does not have the domain on the search list.

A possible solution would be to replace it for `ansible_nodename` or `inventory_hostname`.

**Comment by curt-matthews** [comment]
Pull #27 by A-beck addresses this issue.
