### ISSUE TITLE
Improve repo code for cfme-rolling-os-update-and-upgrade.yml

### ISSUE THREAD

**Issue by curt-matthews** [RedHatOfficial/ansible-redhat_cloudforms#8]
Need to improve repo code design to automatically choose the correct version when using cfme-rolling-os-update-and-upgrade.yml.  The version is currently hardcoded into the playbook.

**Comment by curt-matthews** [comment]
Could also remove the repo code and make the assumption the correct repos are enabled.  Thoughts @itewk @henrygrover ?

**Comment by curt-matthews** [comment]
Done.

**Comment by itewk** [comment]
@curt-matthews just so you know if you put the issue number in the git commit message it will link to the issue here in git. so like adding "issue #8" in the comment.
